name: Sync

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨 0 点运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Clone Bitbucket repository
        run: |
          git clone https://bitbucket.org/odedevs/ode.git
          cd ode
          git remote add upstream https://bitbucket.org/odedevs/ode.git

      - name: Fetch changes from Bitbucket
        run: git fetch upstream

      - name: Merge changes from Bitbucket
        run: git merge upstream/master

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Sync from Bitbucket"
          git push origin master
