name: Sync

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨 0 点运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Merge Push
        run: |
          git remote add bitbucket https://bitbucket.org/odedevs/ode.git
          git fetch bitbucket
          git merge bitbucket/master -X theirs
          git push origin master
